config/routes.rb
Rails.application.routes.draw do
  
  
  resources :ta_users, only: [:new, :create, :edit, :update] do
    resources :help_requests
  end 
  
  
  resources :ta_help_requests
  get '/complete_requests' => 'ta_help_requests#complete_requests'
  resources :students, only: [:new, :create, :edit, :update]do
    resources :help_requests
  end

  
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
    delete :destroy_ta, on: :collection
  end
  
  get '/login_as_student' => 'sessions#new_student'
  get '/login_as_ta' => 'sessions#new_ta_user'
  resources :home, only: [:new, :index] 
  get '/student_index' => 'home#student_index'
  root "home#student_index"

  resources :help_requests

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_ta!, only: :index
  before_action :authenticate_student!, only: :student_index
  
  def new
    render :layout => 'external'
  end

  def index
   @pending_hrs = current_user.help_requests.where("is_complete = false")
   @ta = current_user
  end
  
  def student_index   
    @available = TaUser.available
    #@available_tas = render json: @available, each_serializer: TaSerializer, root: false
  end
    #@ta = TaUser.find(params[:ta_user_id])
    #@hrs = @ta.help_requests.all
    #@pending_hrs = @hrs.where("is_complete = false")

end

app/views/home/index.html.haml
=#-if @ta.is_available? 
=#  = button_to "Go Offline", ta_user_path(id: @ta.id, ta_user: { is_available: false }), method: :patch, class: "btn btn-danger online"
=#-else
=#  = button_to "Go Online", ta_user_path(id: @ta.id, ta_user: { is_available: true }), method: :patch, class: "btn btn-info online"
=#
= react_component 'TaHrIndexPage', {hrs: @pending_hrs, ta: @ta }

app/views/home/new.html.haml
.choose-path
  = link_to "Sign Up as a Young Padawan ( Student )", new_student_path, class: "btn btn-warning"
  %br
  = link_to "Sign Up as a Jedi Master (Teaching Assistant)", new_ta_user_path, class: "btn btn-info"

app/views/home/student_index.html.erb
<div class="student-index">
  <div class="row">
  <%= react_component 'StudentHrIndexPage', {tas: @available_tas} %>
  <%# react_component 'StudentHrs', {student_hrs: @hr_array.to_json } %>  
  <%#  -@available_tas.each do |ta| %>
<%#    .col-md-6 %>
<%#      %h2 Help Requests for #{ta.full_name} %>
<%#      -ta.help_requests.where("is_complete = false").each do |hr| %>
<%#        %h4 #{hr.description} %>
<%#        %h6 -Asked by: #{hr.student.full_name} %>
<%#      =simple_form_for [current_user, HelpRequest.new] do |f| %>
<%#        =f.input :description %>
<%#        =f.hidden_field :ta_user_id, :value => ta.id %>
<%#        =f.submit %>

</div>
</div>
<script>
  window.currentUser = <%= UserSerializer.new(current_user, root: false).to_json.html_safe %>
</script>