config/routes.rb
Rails.application.routes.draw do
  
  
  resources :ta_users, only: [:new, :create, :edit, :update] do
    resources :help_requests
  end 
  
  
  resources :ta_help_requests
  get '/complete_requests' => 'ta_help_requests#complete_requests'
  resources :students, only: [:new, :create, :edit, :update]do
    resources :help_requests
  end

  
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
    delete :destroy_ta, on: :collection
  end
  
  get '/login_as_student' => 'sessions#new_student'
  get '/login_as_ta' => 'sessions#new_ta_user'
  resources :home, only: [:new, :index] 
  get '/student_index' => 'home#student_index'
  root "home#student_index"

  resources :help_requests

end

app/controllers/ta_help_requests_controller.rb
class TaHelpRequestsController < ApplicationController
  
  before_action :authenticate_ta!
  before_action :find_hr, only: [:edit, :update, :destroy]
  
  def index
    @pending_hrs = current_user.help_requests.where(is_complete: false)
    #@ta = current_user
    render json: @pending_hrs
  end
  def complete_requests
    @complete_hrs = current_user.help_requests.where(is_complete: true).order("created_at DESC").limit(6)
    #@ta = current_user
    render json: @complete_hrs
  end
  def update 
    if @help_request.ta_user && @help_request.update(help_request_params)
      render nothing: true 
      #redirect_to ta_help_requests_path, notice: " Done!"
    else
      flash.now[:alert] = "Cant update this HR"
      render :index
    end
  end

  def destroy
    if @help_request.ta_user && @help_request.destroy 
      redirect_to ta_help_requests_path, notice: "Deleted HR"
    else
      flash.now[:alert] = "Cant delete this HR"
      render :index
    end
  end
 
  private
    def help_request_params
      help_request_params = params.require(:help_request).permit(:description, :student_id, :is_complete)
    end
    def find_hr
    @help_request = current_user.help_requests.find_by_id(params[:id])
    redirect_to root_path, alert: "Access denied, foo" unless @help_request
    end
end

app/views/ta_help_requests/index.html.haml
=#-if @ta.is_available? 
=#  = button_to "Go Offline", ta_user_path(id: @ta.id, ta_user: { is_available: false }), method: :patch, class: "btn btn-danger"
=#-else
=#  = button_to "Go Online", ta_user_path(id: @ta.id, ta_user: { is_available: true }), method: :patch, class: "btn btn-info"
=#
=#= react_component 'TaHrIndexPage', {hrs: @pending_hrs}
=#
=#-@pending_hrs.each do |hr|
=#  %h4 #{ hr.description }
=#  %h5 Asked by #{ hr.student.full_name }
=#  = button_to "Mark as done", ta_help_request_path(id: hr.id, help_request: { is_complete: true }), method: :patch, class: "btn btn-primary btn-sm"