config/routes.rb
Rails.application.routes.draw do
  
  
  resources :ta_users, only: [:new, :create, :edit, :update] do
    resources :help_requests
  end 
  
  
  resources :ta_help_requests
  get '/complete_requests' => 'ta_help_requests#complete_requests'
  resources :students, only: [:new, :create, :edit, :update]do
    resources :help_requests
  end

  
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
    delete :destroy_ta, on: :collection
  end
  
  get '/login_as_student' => 'sessions#new_student'
  get '/login_as_ta' => 'sessions#new_ta_user'
  resources :home, only: [:new, :index] 
  get '/student_index' => 'home#student_index'
  root "home#student_index"

  resources :help_requests

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TATool-eine
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #wrap
      %nav.navbar.navbar-inverse
        .container
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button", "aria-expanded" => "true"}
            %span.sr-only 
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} 
            =image_tag("logo.jpg") 
          .pull-right
            .collapse.navbar-collapse{:id => "bs-example-navbar-collapse-1", "aria-expanded" => "true"}
              %ul.nav.navbar-nav
                - if student_signed_in?
                  %li.greeting-1
                    \ Hello apprentice
                    \#{current_user.first_name if current_user.first_name}
                  %li= link_to "Sign Out", sessions_path, method: :delete
                -elsif ta_signed_in?
                  %li.greeting-1
                    \ Hey there Jedi Master
                    \#{current_user.first_name if current_user.first_name}
                  %li= link_to "Sign Out", destroy_ta_sessions_path, method: :delete
                - else
                  %li= link_to "Student Login", login_as_student_path 
                  %li= link_to "Jedi Login ", login_as_ta_path 
                  %li= link_to "Sign Up", new_home_path
      .container   
        - if flash[:notice]
          .alert.alert-success= flash[:notice]
        - elsif flash[:alert]
          .alert.alert-danger= flash[:alert]
        = yield
    #footer
      .container
        .text-muted
          %p
            TATool-eine courtesy of 
            %a{:href => "https://github.com/zeus-"} Zeus

app/views/layouts/external.html.haml
!!!
%html
  %head
    %title TATool-eine
    = stylesheet_link_tag 'external', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #wrap
      %nav.navbar.navbar-inverse
        .container
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button", "aria-expanded" => "true"}
            %span.sr-only 
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} 
            =image_tag("logo.jpg") 
          .pull-right
            .collapse.navbar-collapse{:id => "bs-example-navbar-collapse-1", "aria-expanded" => "true"}
              %ul.nav.navbar-nav
                - if student_signed_in?
                  %li.greeting-1
                    \ Hello apprentice
                    \#{current_user.first_name if current_user.first_name}
                  %li= link_to "Sign Out", sessions_path, method: :delete
                -elsif ta_signed_in?
                  %li.greeting-1
                    \ Hey there Jedi Master
                    \#{current_user.first_name if current_user.first_name}
                  %li= link_to "Sign Out", destroy_ta_sessions_path, method: :delete
                - else
                  %li= link_to "Student Login", login_as_student_path 
                  %li= link_to "Jedi Login ", login_as_ta_path 
                  %li= link_to "Sign Up", new_home_path
      .container   
        - if flash[:notice]
          .alert.alert-success= flash[:notice]
        - elsif flash[:alert]
          .alert.alert-danger= flash[:alert]
        = yield
    #footer
      .container
        .text-muted
          %p
            TATool-eine courtesy of 
            %a{:href => "https://github.com/zeus-"} Zeus